#debug: true

build:
  image: firecyberice/rpi-docker:1.10.0-dev
  extra_hosts:
    - docker
  environment:
    - DOCKER_HOST=tcp://localhost:2375
  commands:
    - apk update && apk add git file
    - export VERSION=$(cat VERSION)
    - export BUILD_RESULTS=/drone/src/buildresult
    - export TIMESTAMP=$(date +"%Y-%m-%d_%H%M")
    - export REPO=$(git rev-parse --short HEAD)
    - git clone -b ${VERSION} https://github.com/crosbymichael/dockerui
    - export BUILD_DIR=${BUILD_RESULTS}/arm-binaries/dockerui/${TIMESTAMP}_${REPO}
    - mkdir -p ${BUILD_DIR}
    - cd dockerui
#    - echo "+++++ remove existing binary and dist folder +++++"
#    - rm -rf dist dockerui
#    - mkdir dist/
#    - rm -f dist/dockerui
    - echo "+++++ build binary +++++"
    - CIDbin=$(docker run -dit -v $(pwd):/gopath/src/github.com/crosbymichael/dockerui/ hypriot/rpi-golang:1.4.2 bash -c "cd /gopath/src/github.com/crosbymichael/dockerui && CGO_ENABLED=0 go build -a --installsuffix cgo --ldflags='-s' .")
    - echo "+++++ build website +++++"
#    - cp dockerui dist/
    - CIDweb=$(docker run -dit -v $(pwd):/dockerui/ hypriot/rpi-node:4.1.2 bash -c "cd /dockerui && npm install -g grunt-cli && npm install && grunt build")
    - echo "+++++ docker runs completed +++++"
    - pwd && ls -la
    - mkdir -p /drone/src/github.com/hypriot/rpi-dockerui/content/
    - cp -r dist/* /drone/src/github.com/hypriot/rpi-dockerui/content/
    - ls -la /drone/src/github.com/hypriot/rpi-dockerui/content/
    - file /drone/src/github.com/hypriot/rpi-dockerui/content/dockerui || true
    - cp dockerui /drone/src/github.com/hypriot/rpi-dockerui/content/
    - ls -la /drone/src/github.com/hypriot/rpi-dockerui/content/
    - file /drone/src/github.com/hypriot/rpi-dockerui/content/dockerui || true
    - pwd
    - echo "+++++ create tar +++++"
    - tar czf ${BUILD_DIR}/dockerui.tar.gz dockerui dist/
    - cd ${BUILD_DIR} && sha256sum dockerui.tar.gz > dockerui.tar.gz.sha256
    - echo ${BUILD_DIR}
    - ls -la ${BUILD_DIR}


compose:
  docker:
    privileged: true
    image: firecyberice/rpi-docker:1.10.0-dev-dind

publish:
  docker:
#    environment:
#      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-dockerui
    tag:
      - v0.9.0
      - latest
    save:
      file: /drone/src/buildresult/docker-images/dockerui_image.tar
    when:
      branch: master

  s3:
    acl: public-read
    region: $$AWS_DEFAULT_REGION
    bucket: $$AWS_BUCKET
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: /drone/src/buildresult
    target: /
    recursive: true
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: buildstatus
    username: Drone
    when:
      started: false
      success: true
      failure: true

